sudo: required

services:
  - docker

# https://ethereum.github.io/go-ethereum/downloads/
env:
  matrix:
    - ARCH=arm   QEMU=qemu-arm-static     BASE_IMAGE=arm32v7/debian:buster-slim  GETH_SOURCE=geth-alltools-linux-arm7-1.9.9-01744997
    - ARCH=arm64 QEMU=qemu-aarch64-static BASE_IMAGE=arm64v8/debian:buster-slim  GETH_SOURCE=geth-alltools-linux-arm64-1.9.9-01744997
    - ARCH=amd64 QEMU=qemu-fake-static    BASE_IMAGE=amd64/debian:buster-slim    GETH_SOURCE=geth-alltools-linux-arm64-1.9.9-01744997.tar.gz

script:
  - ./travis-build.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi
