services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

# pulls from binaries built at:
# https://ethereum.github.io/go-ethereum/downloads/
stages:
  - name: build
  - name: test
    if: (true = false)  #force the tests to skip for now
  - name: package
    if: ((tag IS present) AND (branch = master))

jobs:
  include:
    - &build-image
      stage: build
      env: 
        - ARCH=arm   QEMU=qemu-arm-static     BASE_IMAGE=arm32v7/debian:buster-slim  GETH_SOURCE=geth-alltools-linux-arm7-1.9.9-01744997
      script: ./travis-build.sh
      after_success:
        - >
          if [ -n "$TRAVIS_TAG" ]; then
            travis_retry timeout 5m echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin
            ./travis-deploy.sh
            echo "Deployed $ARCH"
          fi
    - <<: *build-image
      env:
        - ARCH=arm64 QEMU=qemu-aarch64-static BASE_IMAGE=arm64v8/debian:buster-slim  GETH_SOURCE=geth-alltools-linux-arm64-1.9.9-01744997
    - <<: *build-image
      env:
        - ARCH=amd64 QEMU=qemu-fake-static    BASE_IMAGE=amd64/debian:buster-slim    GETH_SOURCE=geth-alltools-linux-amd64-1.9.9-01744997
    - stage: test
      script: echo "Skip tests"
    - stage: package
      script: ./travis-package.sh

